version: "3"

services:
  app:
    image: fast-api-template
    ports:
      - 3000:3000
    networks:
      - network
    environment:
      APP_STAGE: prod
      APP_PORT: 3000
    links:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

networks:
  network:

volumes:
  grafana_data:
