scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "fast-api-template"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["app:3000"]
